# Generated by Django 5.1.7 on 2025-08-04 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccioninventario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.unidades'),
        ),
        migrations.AddField(
            model_name='stock',
            name='unidad_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.unidadesventa'),
        ),
        migrations.AddField(
            model_name='precioporunidad',
            name='unidad_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.unidadesventa'),
        ),
        migrations.AddField(
            model_name='variacionproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.stock'),
        ),
    ]
