# Generated by Django 5.1.7 on 2025-08-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('capacidad_tanque', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('ruta', models.JSONField(default=list)),
                ('viaje_completado', models.BooleanField(default=False)),
                ('fecha_viaje', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
