# Generated by Django 5.1.7 on 2025-08-04 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutas_gps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='camiones',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ubicacioncamion',
            name='camion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locaciones', to='rutas_gps.camiones'),
        ),
    ]
