# Generated by Django 5.1.7 on 2025-08-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas_gps', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camiones',
            name='gasolina_actual',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ubicacioncamion',
            name='gasolina_fin',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ubicacioncamion',
            name='gasolina_inicio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ubicacioncamion',
            name='porcentaje_ahorrado',
            field=models.FloatField(default=0),
        ),
    ]
