# Generated by Django 5.1.7 on 2025-08-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas_gps', '0003_camiones_gasolina_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacioncamion',
            name='duracion_viaje',
            field=models.FloatField(default=0),
        ),
    ]
