# Generated by Django 5.1.7 on 2025-08-04 15:25

import clientes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tiendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente', models.CharField(max_length=100)),
                ('RIF', models.CharField(max_length=12, unique=True, validators=[clientes.models.validar_rif])),
                ('Direccion', models.TextField()),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20, validators=[clientes.models.validar_nombre])),
                ('Apellido', models.CharField(max_length=20, validators=[clientes.models.validar_nombre])),
                ('Cedula', models.CharField(max_length=12, unique=True, validators=[clientes.models.validar_cedula])),
                ('Correo', models.EmailField(max_length=254, unique=True, validators=[clientes.models.validar_correo])),
                ('Telefono', models.CharField(max_length=15, validators=[clientes.models.validar_telefono])),
                ('Tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.tiendas')),
            ],
        ),
    ]
